# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment


on:
  workflow_dispatch:


jobs:
  
  armdeploy:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4 
      
      - name: Azure Login
        uses: Azure/Login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      
      